### ISSUE TITLE
phyton

### ISSUE THREAD

**Issue by AliArdal** [riseOnlineBots/KO-upgrade#1]
import time
import keyboard

def skill1():
    keyboard.press('1')
    time.sleep(0.005)
    keyboard.release('1')
    time.sleep(0.01)

def skill2():
    keyboard.press('2')
    time.sleep(0.01)
    keyboard.release('2')
    time.sleep(0.2)

def skill4():
    keyboard.press('4')
    time.sleep(0.01)
    keyboard.release('4')
    time.sleep(0.2)

def canavar_sec():
    keyboard.press('Z')
    time.sleep(0.1)
    keyboard.release('Z')
    time.sleep(0.1)

time.sleep(3)
skill2()

counter = 0
while True:
    canavar_sec()
    time.sleep(0.1)
    skill1()
    time.sleep(0.01)

    counter += 1
    if counter % 35 == 0:
        skill4()

    if counter % 120 == 0:  
        skill2() ///////////////////////////////// burda istediğim en alttaki skil2 fonksiyonun ilk başladıgı andan 120 saniye sonra tekrar tıklaması ve bu sonsuza kadar devam etmesi bu süreçte diğer fonksyonlar devam etmeli

**Comment by AlicanBalik** [comment]
Su an ki kodun tek bir Thread'de calisiyor. Istedigini elde etmek icin yeni Thread'ler aktif etmen gerekli.

Yapmak istedigin bot skill vuracak sadece sanirim. Paylasmis oldugum skill/ts bot projesini direk kopyalayip, kendi istedigin gibi duzenleyebilirsin - https://github.com/riseOnlineBots/KO-bot/blob/vanilla/main.py.

**Comment by AliArdal** [comment]
burda kodum çalışıyor zaten tek sıkıntısı counter içinde yazdıgım skil2 fonksiyonu 120 saniyede değilde başka bir zaman aralıgında tıklıyor olması

**Comment by AlicanBalik** [comment]
Cunku mevcut Thread'i uyutuyorsun. Her uyutman, gecikmeye neden olur. Hem canavar_sec hem de skill1 fonksiyonlarinda uyuduyorsun Thread'i. O yuzden tam 120 saniyede degil baska bir surede basar. 

Sureli kontrol ettirmek istiyorsan Time kullanman gerekli.

Ornek kod:

```
from datetime import datetime, timedelta

skill_2_suresi = 120
skill_2_kullanim_zamani = datetime.now()
```

`if counter % 120 == 0:` yerine `if datetime.now() >= next_ts_use:` ile degistir.

```
if datetime.now() >= next_ts_use:
   skill2()
   skill_2_kullanim_zamani = datetime.now() + timedelta(seconds=skill_2_suresi)
```

**Comment by AlicanBalik** [comment]
> burda kodum çalışıyor zaten tek sıkıntısı counter içinde yazdıgım skil2 fonksiyonu 120 saniyede değilde başka bir zaman aralıgında tıklıyor olması

Cunku mevcut Thread'i uyutuyorsun. Her uyutman gecikmeye neden olur. Hem canavar_sec hem de skill1 fonksiyonlarinda uyutuyorsun Thread'i. O yuzden tam 120 saniyede degil baska bir surede basar. 

Sureli kontrol ettirmek istiyorsan Time kullanman gerekli.

Ornek kod:

```
from datetime import datetime, timedelta

skill_2_suresi = 120
skill_2_kullanim_zamani = datetime.now()
```

`if counter % 120 == 0:` yerine `if datetime.now() >= skill_2_kullanim_zamani:` ile degistir.

```
if datetime.now() >= skill_2_kullanim_zamani:
   skill2()
   skill_2_kullanim_zamani = datetime.now() + timedelta(seconds=skill_2_suresi)
```
